name: Echo Example

on:
  workflow_dispatch:
jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run echo command
        run: echo "Hello, this is a simple GitHub Actions workflow!"
